[target.aarch64-unknown-linux-gnu]
pre-build = [
    "curl -sL https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64 -o /usr/local/bin/tailwindcss",
    "chmod +x /usr/local/bin/tailwindcss"
]
